modLoader = "javafml"
loaderVersion = "[4,)"
license = "ARR"

[[mods]]
modId = "peekinside"
version = "1.0.0"
displayName = "Container Preview"
authors = "Xeonz"
description = "Preview the contents of container items directly in tooltips."
logoFile = "icon.png"

[[mixins]]
config = "peekinside.mixins.json"
[[mixins]]
config = "peekinside.neoforge.mixins.json"

[[dependencies.peekinside]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.peekinside]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11, 1.22)"
ordering = "NONE"
side = "BOTH"
